repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(app|tests)/
      - id: ruff-format
        files: ^(app|tests)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
        args: [--install-types, --non-interactive]
        files: ^(app|tests)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        files: ^(app|tests)/
      - id: trailing-whitespace
        files: ^(app|tests)/
      - id: check-yaml
        files: ^(app|tests|\.github/)
      - id: check-toml
        files: ^(pyproject\.toml)$
      - id: check-json
        files: ^(app|tests|\.github/)

exclude: >
  (?x)^(
    \.venv/|
    venv/|
    img-cache/|
    \.git/|
    .*\.zip$|.*\.tgz$|.*\.tar(\.gz)?$|
    .*\.sqlite3?$|
    .*\.log$
  )
