name: CI

on:
  pull_request:
  push:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev deps
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: ruff check .
      - name: Type check
        run: mypy .
      - name: Tests
        run: pytest -q
